trino:
  target: dev
  outputs:
    dev:
      type: trino
      method: ldap
      user: anyuser
      password: anypassword
      host: trino-gateway-hostname
      port: 443
      database: iceberg
      schema: silver
      threads: 8
      http_scheme: https
      session_properties:
        query_max_run_time: 5d
        exchange_compression: True
